# Generated by Django 5.2.5 on 2025-11-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userregistration_date_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
